name: PR Test and Coverage

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run jest test and coverage
        run: |
          npx jest --ci --testLocationInResults --noStackTrace > jest_output.txt
          npx jest --coverage --coverageReporters=text-summary > coverage_summary.txt

      - name: Format output and comment
        run: |
          echo '✅ 테스트 결과' > pr_comment.txt
          grep -E '^(PASS|FAIL)' jest_output.txt >> pr_comment.txt

          echo -e '\n🧪 커버리지 요약' >> pr_comment.txt
          cat coverage_summary.txt >> pr_comment.txt

      - name: Post PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: pr_comment.txt
